package com.paie.calcul_paie.model;
// Generated 10 mai 2018 19:43:39 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Cotisations generated by hbm2java
 */
@Entity
@Table(name = "cotisations")
public class Cotisations implements java.io.Serializable {

	private Long id;
	private int version;
	private double csgd;
	private double csgrds;
	private double retraite;
	private double secu;

	public Cotisations() {
	}

	public Cotisations(double csgd, double csgrds, double retraite, double secu) {
		this.csgd = csgd;
		this.csgrds = csgrds;
		this.retraite = retraite;
		this.secu = secu;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Column(name = "CSGD", nullable = false, precision = 22, scale = 0)
	public double getCsgd() {
		return this.csgd;
	}

	public void setCsgd(double csgd) {
		this.csgd = csgd;
	}

	@Column(name = "CSGRDS", nullable = false, precision = 22, scale = 0)
	public double getCsgrds() {
		return this.csgrds;
	}

	public void setCsgrds(double csgrds) {
		this.csgrds = csgrds;
	}

	@Column(name = "RETRAITE", nullable = false, precision = 22, scale = 0)
	public double getRetraite() {
		return this.retraite;
	}

	public void setRetraite(double retraite) {
		this.retraite = retraite;
	}

	@Column(name = "SECU", nullable = false, precision = 22, scale = 0)
	public double getSecu() {
		return this.secu;
	}

	public void setSecu(double secu) {
		this.secu = secu;
	}

}
