package com.paie.calcul_paie.model;
// Generated 10 mai 2018 19:43:39 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Employes generated by hbm2java
 */
@Entity
@Table(name = "employes", uniqueConstraints = @UniqueConstraint(columnNames = "SS"))
public class Employes implements java.io.Serializable {

	private Long id;
	private int version;
	private Indemnites indemnites;
	private String adresse;
	private String cp;
	private String nom;
	private String prenom;
	private String ss;
	private String ville;
	private Long indemnitesId;

	public Employes() {
	}

	public Employes(Indemnites indemnites, String adresse, String cp, String nom, String prenom, String ss,
			String ville) {
		this.indemnites = indemnites;
		this.adresse = adresse;
		this.cp = cp;
		this.nom = nom;
		this.prenom = prenom;
		this.ss = ss;
		this.ville = ville;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INDEMNITE_ID", nullable = false)
	public Indemnites getIndemnites() {
		return this.indemnites;
	}

	public void setIndemnites(Indemnites indemnites) {
		this.indemnites = indemnites;
	}

	@Column(name = "ADRESSE", nullable = false, length = 50)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "CP", nullable = false, length = 5)
	public String getCp() {
		return this.cp;
	}

	public void setCp(String cp) {
		this.cp = cp;
	}

	@Column(name = "NOM", nullable = false, length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", nullable = false, length = 30)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "SS", unique = true, nullable = false, length = 15)
	public String getSs() {
		return this.ss;
	}

	public void setSs(String ss) {
		this.ss = ss;
	}

	@Column(name = "VILLE", nullable = false, length = 20)
	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}
	
	@Column(name="INDEMNITE_ID", updatable=false, insertable=false,nullable=false)
	public Long getIndemnitesId() {
		return indemnitesId;
	}

	public void setIndemnitesId(Long indemnitesId) {
		this.indemnitesId = indemnitesId;
	}

	@Override
	public String toString() {
		return String.format("Employé=[id=%s, version=%s, prénom=%s, nom=%s, adresse=%s, ville=%s, code postal=%s, indemnite=\r\n" + 
				"%s]", id,version,prenom,nom, adresse, ville, cp, indemnites);
	}

}
