package com.paie.calcul_paie.model;
// Generated 10 mai 2018 19:43:39 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Indemnites generated by hbm2java
 */
@Entity
@Table(name = "indemnites", uniqueConstraints = @UniqueConstraint(columnNames = "INDICE"))
public class Indemnites implements java.io.Serializable {

	private Long id;
	private int version;
	private double baseHeure;
	private double entretienJour;
	private double indemnitesCp;
	private int indice;
	private double repasJour;
	private Set<Employes> employeses = new HashSet<Employes>(0);

	public Indemnites() {
	}

	public Indemnites(double baseHeure, double entretienJour, double indemnitesCp, int indice, double repasJour) {
		this.baseHeure = baseHeure;
		this.entretienJour = entretienJour;
		this.indemnitesCp = indemnitesCp;
		this.indice = indice;
		this.repasJour = repasJour;
	}

	public Indemnites(double baseHeure, double entretienJour, double indemnitesCp, int indice, double repasJour,
			Set<Employes> employeses) {
		this.baseHeure = baseHeure;
		this.entretienJour = entretienJour;
		this.indemnitesCp = indemnitesCp;
		this.indice = indice;
		this.repasJour = repasJour;
		this.employeses = employeses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Column(name = "BASE_HEURE", nullable = false, precision = 22, scale = 0)
	public double getBaseHeure() {
		return this.baseHeure;
	}

	public void setBaseHeure(double baseHeure) {
		this.baseHeure = baseHeure;
	}

	@Column(name = "ENTRETIEN_JOUR", nullable = false, precision = 22, scale = 0)
	public double getEntretienJour() {
		return this.entretienJour;
	}

	public void setEntretienJour(double entretienJour) {
		this.entretienJour = entretienJour;
	}

	@Column(name = "INDEMNITES_CP", nullable = false, precision = 22, scale = 0)
	public double getIndemnitesCp() {
		return this.indemnitesCp;
	}

	public void setIndemnitesCp(double indemnitesCp) {
		this.indemnitesCp = indemnitesCp;
	}

	@Column(name = "INDICE", unique = true, nullable = false)
	public int getIndice() {
		return this.indice;
	}

	public void setIndice(int indice) {
		this.indice = indice;
	}

	@Column(name = "REPAS_JOUR", nullable = false, precision = 22, scale = 0)
	public double getRepasJour() {
		return this.repasJour;
	}

	public void setRepasJour(double repasJour) {
		this.repasJour = repasJour;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "indemnites")
	public Set<Employes> getEmployeses() {
		return this.employeses;
	}

	public void setEmployeses(Set<Employes> employeses) {
		this.employeses = employeses;
	}
	
	@Override
	public String toString() {
		return String.format("Indemnités=[id=%s, version=%s, baseHeure=%s, entretienJour=%s, indemnitesCp=%s, "
				+ "indice=%s, repasJour=%s]", id,version,baseHeure,entretienJour, 
				indemnitesCp, indice, repasJour);

	}

}
